# Generated by Django 4.2.16 on 2026-07-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
    ]
